language: node_js
dist: trusty
node_js: 8.9
sudo: true

addons:
  firefox: latest
  google-chrome: latest

before_install:
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

script:
  # xvfb-run is needed for headless testing with Chrome and Firefox
  - xvfb-run yarn test

after_script:
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
      xvfb-run yarn run check:tests:saucelabs;
    fi
  - greenkeeper-lockfile-upload

notifications:
  email:
    on_success: never
